services:
  backend:
    build: backend/.
    ports:
      - "3001:3001"
  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: nest-boilerplate
    ports:
      - "5434:5432"
  nginx:
    build: nginx/.
    ports:
      - "81:80"
    links: # được sử dụng để xác định các kết nối từ dịch vụ nginx đến các dịch vụ frontend và backend.
      - frontend
      - backend
